C    DUMMY PLOT INTERFACE ROUTINES
C
      SUBROUTINE PLTON(XMIN,XMAX,YMIN,YMAX)
      RETURN
      END
C
      SUBROUTINE PLTMOV(X,Y)
      RETURN
      END
C
      SUBROUTINE PLTLIN(X,Y)
      RETURN
      END
C
      SUBROUTINE PLTPEN(IPEN)
      RETURN
      END
C
      SUBROUTINE PLTPT(X,Y,LABEL,IMARK)
C
C    PLOTS POINT AT (X,Y), ANNOTATING IT AS FOLLOWS:
C    IMARK = 1  NO CROSS, INTEGER LABEL
C            2  NO CROSS, A4 LABEL
C            3  CROSS
C            4  CROSS, INTEGER LABEL
C            5  CROSS, A4 LABEL
C
      RETURN
      END
C
      SUBROUTINE PLTOFF
      RETURN
      END
